
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA NUMERO VER FAL CODIGO CCOR ACOR COMA DOSPinicio : jsonjson : ACOR contenido CCORcontenido : contenido COMA CADENA DOSP valorcontenido : CADENA DOSP valorvalor : CADENAvalor : jsonvalor : NUMEROvalor : CODIGOvalor : VERvalor : FAL'
    
_lr_action_items = {'ACOR':([0,8,17,],[3,3,3,]),'$end':([1,2,6,],[0,-1,-2,]),'CADENA':([3,7,8,17,],[5,9,10,10,]),'CCOR':([4,6,10,11,12,13,14,15,16,18,],[6,-2,-5,-4,-6,-7,-8,-9,-10,-3,]),'COMA':([4,6,10,11,12,13,14,15,16,18,],[7,-2,-5,-4,-6,-7,-8,-9,-10,-3,]),'DOSP':([5,9,],[8,17,]),'NUMERO':([8,17,],[13,13,]),'CODIGO':([8,17,],[14,14,]),'VER':([8,17,],[15,15,]),'FAL':([8,17,],[16,16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'inicio':([0,],[1,]),'json':([0,8,17,],[2,12,12,]),'contenido':([3,],[4,]),'valor':([8,17,],[11,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> inicio","S'",1,None,None,None),
  ('inicio -> json','inicio',1,'p_inicio','Comunicacion.py',54),
  ('json -> ACOR contenido CCOR','json',3,'p_json','Comunicacion.py',58),
  ('contenido -> contenido COMA CADENA DOSP valor','contenido',5,'p_contenido','Comunicacion.py',61),
  ('contenido -> CADENA DOSP valor','contenido',3,'p_contenido_2','Comunicacion.py',65),
  ('valor -> CADENA','valor',1,'p_valor','Comunicacion.py',73),
  ('valor -> json','valor',1,'p_valor2','Comunicacion.py',77),
  ('valor -> NUMERO','valor',1,'p_valor3','Comunicacion.py',81),
  ('valor -> CODIGO','valor',1,'p_valor4','Comunicacion.py',86),
  ('valor -> VER','valor',1,'p_valor5','Comunicacion.py',90),
  ('valor -> FAL','valor',1,'p_valor6','Comunicacion.py',94),
]
